services:

  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=transactions

  transactions:
    build:
      context: transactions-service/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      # General
      - API_NAME="Transactions Service"
      - API_HOST=0.0.0.0
      - API_PORT=8000
      # Database
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transactions
    depends_on:
      - db

volumes:
  app-db-data:
